# Numpy


In [1]:
import numpy as np


In [2]:
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0, 1]

np.int64(6)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 32,  7]])

# Array creation : Conversion from other python structure

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [16]:
np.array({34,67,34})

array({34, 67}, dtype=object)

In [17]:
zeros = np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
rng = np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace = np.linspace(1,5,12)

In [26]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
lspace = np.linspace(1,50,10)

In [28]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
lspace = np.linspace(1,4,4)

In [30]:
lspace

array([1., 2., 3., 4.])

In [31]:
lspace = np.linspace(1,5,4)

In [32]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [34]:
emp = np.empty((4,6))

In [35]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        2.22522461e-306, 7.56587585e-307, 7.56593017e-307],
       [1.60217812e-306, 1.11261095e-306, 1.42417221e-306,
        1.37961641e-306, 2.22522597e-306, 1.33511969e-306],
       [6.23037657e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 2.22522597e-306, 1.33511290e-306],
       [1.69118108e-306, 9.34604358e-307, 9.34598925e-307,
        1.24612081e-306, 2.22522596e-306, 8.34443015e-308]])

In [36]:
emp_like = np.empty_like(lspace)

In [38]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [39]:
ide = np.identity(45)

In [40]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [41]:
ide.shape

(45, 45)

In [42]:
arr = np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [47]:
arr = arr.reshape(3,33)

In [48]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [49]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr = arr.ravel()

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
arr.shape

(99,)

In [53]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [56]:
arr = np.array(x)

In [57]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
arr.sum(axis = 0)

array([12,  8,  9])

In [59]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [61]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [62]:
ar.flat

In [63]:
for item in ar.flat:
    print(item)


1
2
3
4
5
6
7
1
0


In [64]:
arr.ndim

2

In [65]:
ar.ndim

2

In [66]:
ar.ndim

2

In [67]:
ar.size

9

In [69]:
ar.nbytes

72

In [72]:
one = np.array([1,3,4,634,2])

In [73]:
one.argmax()

np.int64(3)

In [74]:
one.argmin()

np.int64(0)

In [75]:
one.argsort()

array([0, 4, 1, 2, 3])

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [78]:
ar.argmin()

np.int64(8)

In [79]:
ar.argmax()

np.int64(6)

In [80]:
ar.argmax(axis = 0)

array([2, 1, 1])

In [81]:
ar.argmax(axis = 1)

array([2, 2, 0])

In [82]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [83]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])